# 配置网关
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: static-service
          uri: lb://static-service
          predicates:
            - Path=/public/**
        - id: carousel-service
          uri: lb://carousel-service
          predicates:
            - Path=/carousel/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: collect-service
          uri: lb://collect-service
          predicates:
            - Path=/collect/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-service  # 订单服务
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: admin-service  # 后台管理服务
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

