ribbon:
  eager-load:
    enabled: true #开启饥饿加载提升第一次访问速度
    clients:
      - search-service #指定开启服务
feign:
  httpclient:
    enabled: true  # 开启httpClient开关,启动连接池,提升feign连接效率!
    max-connections: 200  #最大连接数量
    max-connections-per-route: 50  #单路径最大连接数
  client: #默认 1秒
    config:
      default:
        connectTimeout: 10000 #设置连接超时时间
        readTimeout: 10000 #设置读取数据超时时间
spring:
  profiles:
    active: mq  #激活mq的配置